In [1]:
import pandas as pd
import random as rnd
from matplotlib import pyplot as plt
from matplotlib import mlab
#import pylab as pl
#from decimal import Decimal
#plt.style.use('ggplot')
#plt.rcParams['figure.figsize'] = 10, 6
#import seaborn as sns
import numpy as np
from numpy import linalg as la
#%matplotlib inline
# отключим всякие предупреждения Anaconda
#import warnings
#warnings.filterwarnings('ignore')
import numpy as np
import scipy as sp
from scipy import optimize as opt
from scipy.optimize import basinhopping
from scipy.optimize import differential_evolution
#from scipy.optimize import dual_annealing
import math
from sympy import symbols, diff
from sympy import *

In [2]:
s = 2

In [3]:
bounds = np.array([[-1, 1] for i in range(s)]) 

In [4]:
n = 10 

In [5]:
def k_1(x, y):
    return (x[0] + x[1])*(y[0]*y[1]) 

In [6]:
K = k_1

In [7]:
def phi_1(x):
    return x[0]*x[1] - (4/9)*(x[0] + x[1])

In [8]:
phi = phi_1

In [9]:
b = np.array([[rnd.random() * (bounds[j][1] - bounds[j][0]) + bounds[j][0] for j in range(s)] 
               for i in range(n)]) 
print(b)

[[-0.47988989  0.45654884]
 [ 0.42276251 -0.61392928]
 [ 0.25678547 -0.63352945]
 [-0.37943918  0.42758835]
 [ 0.60601845 -0.16642207]
 [ 0.20320341 -0.57536848]
 [-0.12656837 -0.09386335]
 [-0.08095702 -0.41838485]
 [-0.42842205  0.95739393]
 [ 0.37810723 -0.64953622]]


Здесь сначала генерируем равномерно распределённые на отрезке [-1;1] точки

In [11]:
w1 = np.array([[np.random.uniform(low=-1., high=1.) for j in range(s)] 
               for i in range(n)])
print(w1)

[[ 0.06910128  0.98163289]
 [-0.23173761  0.15826323]
 [-0.76507629 -0.53585601]
 [-0.98103445 -0.51351964]
 [ 0.5638323   0.43080521]
 [ 0.53471898 -0.80805525]
 [ 0.11783162  0.12974821]
 [-0.49548329  0.50166785]
 [ 0.02356415 -0.17143866]
 [-0.37260542 -0.73439736]]


получаем евклидову норму

In [14]:
q = np.array([[sqrt(sum((abs(w1[i]))**2)) for j in range(s-1)]for i in range(n)])
print(q)

[[0.984062046548120]
 [0.280623540792242]
 [0.934068197033362]
 [1.10730800682333]
 [0.709577333734077]
 [0.968957008698983]
 [0.175268048328505]
 [0.705105896969212]
 [0.173050521721343]
 [0.823513376899267]]


нормируем полученные векторы

In [15]:
w = np.array([w1[i]/q[i] for i in range(n)])
print(w)

[[0.0702204454928359 0.997531497765754]
 [-0.825795339999317 0.563969907384616]
 [-0.819079695828829 -0.573679746793412]
 [-0.885963479293380 -0.463755014375444]
 [0.794603036989139 0.607129321979788]
 [0.551850059427974 -0.833943350539676]
 [0.672293763122477 0.740284469691630]
 [-0.702707625085318 0.711478737311912]
 [0.136169205635992 -0.990685594644670]
 [-0.452458250085521 -0.891785586298381]]


In [16]:
def neuron(i, x):            #i - номер базисной функции
    if i == 0:
        return 1
    else:  
        return float(np.dot(w[i-1], x-b[i-1])>0)

In [17]:
e = neuron

In [18]:
m = 100

In [19]:
x_for_int = np.array([[rnd.random() * (bounds[j][1] - bounds[j][0]) + bounds[j][0] for j in range(s)] 
               for i in range(m)]) 

In [20]:
meas = np.prod([bounds[j][1] - bounds[j][0] for j in range(s)])

In [21]:
def integral_of_e_i_e_j(e, i, j):
    return meas * np.mean(np.array([e(i, x) * e(j, x) for x in x_for_int]))

In [22]:
x_for_int_2 = np.array([[rnd.random() * (bounds[j][1] - bounds[j][0]) + bounds[j][0] for j in range(s)] 
               for i in range(m)]) 

In [23]:
def integral_of_K_e_i_e_j(K, e, i, j):
    return meas**2 * np.mean(np.array([[K(x, y) * e(i, x) * e(j, x) for x in x_for_int] for y in x_for_int_2]))

In [24]:
matrix = [[integral_of_e_i_e_j(neuron, i, j) - integral_of_K_e_i_e_j(K, neuron, i, j) for j in range(n+1)] for i in range(n+1)]

TypeError: float() argument must be a string or a number, not 'BooleanFalse'

In [26]:
def integral_of_e_i_phi(e, i, phi):
    return meas * np.mean(np.array([e(i, x) * phi(x) for x in x_for_int]))

In [27]:
right_side = [integral_of_e_i_phi(neuron, i, phi)  for i in range(n+1)]

TypeError: float() argument must be a string or a number, not 'BooleanFalse'

In [28]:
c = np.linalg.solve(matrix, right_side)
print(c)

NameError: name 'matrix' is not defined